In [2]:
import os
import pandas as pd

In [3]:
os.getcwd()

'C:\\Users\\PC 16\\Desktop\\data science'

In [42]:
# QUESTION 2
# a)
df=pd.read_table('World_Bank.txt', skiprows=3)
df=pd.DataFrame(df)
df

,Country,Country Code,Indicator Name,Indicator Code,1968,1969,1970,1971,1972,1973,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
1,Andorra,AND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
2,Afghanistan,AFG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
3,Angola,AGO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008860e+11,1.039110e+11
4,Albania,ALB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,"Yemen, Rep.",YEM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.672565e+10,2.761787e+10,2.872656e+10,2.991436e+10,3.090675e+10,2.624342e+10,2.689160e+10,2.800914e+10,NaN,NaN
260,South Africa,ZAF,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,7.707081e+10,8.003449e+10,8.497844e+10,9.124438e+10,9.848904e+10,1.072510e+11,...,3.402850e+11,3.585260e+11,3.699670e+11,3.642760e+11,3.753490e+11,3.874070e+11,3.960070e+11,4.047680e+11,4.110370e+11,4.163120e+11
261,"Congo, Dem. Rep.",COD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.508024e+10,1.344383e+10,1.629401e+10,1.714358e+10,1.672524e+10,1.689205e+10,...,1.650894e+10,1.754232e+10,1.863448e+10,1.916651e+10,2.052329e+10,2.193213e+10,2.350200e+10,2.550050e+10,2.778776e+10,2.970961e+10
262,Zambia,ZMB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.592975e+09,4.655503e+09,4.539542e+09,4.688093e+09,5.260699e+09,6.136472e+09,...,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
263,Zimbabwe,ZWE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.338344e+09,3.549199e+09,3.600111e+09,3.824915e+09,3.782605e+09,3.968352e+09,...,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

In [20]:
df1=pd.read_csv('Energy.csv')
df1=pd.DataFrame(df1)
df1

,Country,Total Energy Supply,Energy Supply per Capita,%Renewable
0,Afghanistan,3.210000e+08,10.0,78.67
1,Albania,1.020000e+08,35.0,100.00
2,Algeria,1.959000e+09,51.0,0.55
3,American Samoa,NaN,NaN,0.64
4,Andorra,9.000000e+06,121.0,88.70
...,...,...,...,...
222,Viet Nam,2.554000e+09,28.0,45.32
223,Wallis and Futuna Islands,0.000000e+00,26.0,0.00
224,Yemen,3.440000e+08,13.0,0.00
225,Zambia,4.000000e+08,26.0,99.71
226,Zimbabwe,4.800000e+08,32.0,52.54

In [54]:
# b)
joindata=pd.merge(df1,df, on='Country', how='inner')
grouped=joindata.groupby('Country')
print(joindata)

            Country  Total Energy Supply  Energy Supply per Capita  \
0       Afghanistan         3.210000e+08                      10.0
1           Albania         1.020000e+08                      35.0
2           Algeria         1.959000e+09                      51.0
3    American Samoa                  NaN                       NaN
4           Andorra         9.000000e+06                     121.0
..              ...                  ...                       ...
180         Uruguay         1.960000e+08                      58.0
181      Uzbekistan         1.798000e+09                      62.0
182         Vanuatu         3.000000e+06                      10.0
183          Zambia         4.000000e+08                      26.0
184        Zimbabwe         4.800000e+08                      32.0

     %Renewable Country Code                            Indicator Name  \
0         78.67          AFG  GDP at market prices (constant 2010 US$)
1        100.00          ALB  GDP at market prices (constant 2010 US$)
2          0.55          DZA  GDP at market prices (constant 2010 US$)
3          0.64          ASM  GDP at market prices (constant 2010 US$)
4         88.70          AND  GDP at market prices (constant 2010 US$)
..          ...          ...                                       ...
180       71.61          URY  GDP at market prices (constant 2010 US$)
181       21.33          UZB  GDP at market prices (constant 2010 US$)
182       14.71          VUT  GDP at market prices (constant 2010 US$)
183       99.71          ZMB  GDP at market prices (constant 2010 US$)
184       52.54          ZWE  GDP at market prices (constant 2010 US$)

     Indicator Code          1968          1969          1970  ...  \
0    NY.GDP.MKTP.KD           NaN           NaN           NaN  ...
1    NY.GDP.MKTP.KD           NaN           NaN           NaN  ...
2    NY.GDP.MKTP.KD  2.744286e+10  2.370914e+10  1.904199e+10  ...
3    NY.GDP.MKTP.KD           NaN           NaN           NaN  ...
4    NY.GDP.MKTP.KD           NaN           NaN           NaN  ...
..              ...           ...           ...           ...  ...
180  NY.GDP.MKTP.KD  1.389822e+10  1.424471e+10  1.402042e+10  ...
181  NY.GDP.MKTP.KD           NaN           NaN           NaN  ...
182  NY.GDP.MKTP.KD           NaN           NaN           NaN  ...
183  NY.GDP.MKTP.KD  4.592975e+09  4.655503e+09  4.539542e+09  ...
184  NY.GDP.MKTP.KD  3.338344e+09  3.549199e+09  3.600111e+09  ...

             2014          2015          2016          2017          2018  \
0    1.030523e+10  1.172119e+10  1.214448e+10  1.469733e+10  1.593680e+10
1    9.771760e+09  1.034829e+10  1.112752e+10  1.150029e+10  1.192695e+10
2    1.446470e+11  1.495650e+11  1.531550e+11  1.556050e+11  1.612070e+11
3             NaN           NaN           NaN           NaN           NaN
4    4.018196e+09  4.021331e+09  3.675728e+09  3.535389e+09  3.346317e+09
..            ...           ...           ...           ...           ...
180  3.139363e+10  3.344725e+10  3.584747e+10  3.736865e+10  4.028468e+10
181  2.798925e+10  3.076611e+10  3.353506e+10  3.625140e+10  3.933277e+10
182  5.961693e+08  6.270251e+08  6.674589e+08  6.895706e+08  7.008043e+08
183  1.440569e+10  1.560892e+10  1.682234e+10  1.837342e+10  2.026555e+10
184  1.006276e+10  9.695130e+09  7.982103e+09  8.459783e+09  9.422161e+09

             2019          2020          2021          2022          2023
0    1.691113e+10  1.935220e+10  1.973134e+10  1.999032e+10  2.029415e+10
1    1.223109e+10  1.240477e+10  1.254247e+10  1.279331e+10  1.312082e+10
2    1.658820e+11  1.715220e+11  1.763250e+11  1.830250e+11  1.901630e+11
3             NaN           NaN           NaN           NaN           NaN
4    3.185605e+09  3.129538e+09  3.127550e+09           NaN           NaN
..            ...           ...           ...           ...           ...
180  4.236423e+10  4.386315e+10  4.589732e+10  4.738384e+10  4.784927e+10
181  4.259739e+10  4.609038e+10  4.977761e+10  5.380959e+10  5.811436e+10
182  7.093767e+08  7.218245e+08  7.360383e+08  7.529991e+08           NaN
183  2.140358e+10  2.302438e+10  2.420595e+10  2.542227e+10  2.624127e+10
184  1.054391e+10  1.165789e+10  1.218064e+10  1.264939e+10  1.278517e+10

[185 rows x 63 columns]

In [50]:
# c)
joindata['Population']=joindata['Total Energy Supply']/joindata['Energy Supply per Capita']
print(joindata)

            Country  Total Energy Supply  Energy Supply per Capita  \
0       Afghanistan         3.210000e+08                      10.0
1           Albania         1.020000e+08                      35.0
2           Algeria         1.959000e+09                      51.0
3    American Samoa                  NaN                       NaN
4           Andorra         9.000000e+06                     121.0
..              ...                  ...                       ...
180         Uruguay         1.960000e+08                      58.0
181      Uzbekistan         1.798000e+09                      62.0
182         Vanuatu         3.000000e+06                      10.0
183          Zambia         4.000000e+08                      26.0
184        Zimbabwe         4.800000e+08                      32.0

     %Renewable Country Code                            Indicator Name  \
0         78.67          AFG  GDP at market prices (constant 2010 US$)
1        100.00          ALB  GDP at market prices (constant 2010 US$)
2          0.55          DZA  GDP at market prices (constant 2010 US$)
3          0.64          ASM  GDP at market prices (constant 2010 US$)
4         88.70          AND  GDP at market prices (constant 2010 US$)
..          ...          ...                                       ...
180       71.61          URY  GDP at market prices (constant 2010 US$)
181       21.33          UZB  GDP at market prices (constant 2010 US$)
182       14.71          VUT  GDP at market prices (constant 2010 US$)
183       99.71          ZMB  GDP at market prices (constant 2010 US$)
184       52.54          ZWE  GDP at market prices (constant 2010 US$)

     Indicator Code          1968          1969          1970  ...  \
0    NY.GDP.MKTP.KD           NaN           NaN           NaN  ...
1    NY.GDP.MKTP.KD           NaN           NaN           NaN  ...
2    NY.GDP.MKTP.KD  2.744286e+10  2.370914e+10  1.904199e+10  ...
3    NY.GDP.MKTP.KD           NaN           NaN           NaN  ...
4    NY.GDP.MKTP.KD           NaN           NaN           NaN  ...
..              ...           ...           ...           ...  ...
180  NY.GDP.MKTP.KD  1.389822e+10  1.424471e+10  1.402042e+10  ...
181  NY.GDP.MKTP.KD           NaN           NaN           NaN  ...
182  NY.GDP.MKTP.KD           NaN           NaN           NaN  ...
183  NY.GDP.MKTP.KD  4.592975e+09  4.655503e+09  4.539542e+09  ...
184  NY.GDP.MKTP.KD  3.338344e+09  3.549199e+09  3.600111e+09  ...

             2015          2016          2017          2018          2019  \
0    1.172119e+10  1.214448e+10  1.469733e+10  1.593680e+10  1.691113e+10
1    1.034829e+10  1.112752e+10  1.150029e+10  1.192695e+10  1.223109e+10
2    1.495650e+11  1.531550e+11  1.556050e+11  1.612070e+11  1.658820e+11
3             NaN           NaN           NaN           NaN           NaN
4    4.021331e+09  3.675728e+09  3.535389e+09  3.346317e+09  3.185605e+09
..            ...           ...           ...           ...           ...
180  3.344725e+10  3.584747e+10  3.736865e+10  4.028468e+10  4.236423e+10
181  3.076611e+10  3.353506e+10  3.625140e+10  3.933277e+10  4.259739e+10
182  6.270251e+08  6.674589e+08  6.895706e+08  7.008043e+08  7.093767e+08
183  1.560892e+10  1.682234e+10  1.837342e+10  2.026555e+10  2.140358e+10
184  9.695130e+09  7.982103e+09  8.459783e+09  9.422161e+09  1.054391e+10

             2020          2021          2022          2023    Population
0    1.935220e+10  1.973134e+10  1.999032e+10  2.029415e+10  3.210000e+07
1    1.240477e+10  1.254247e+10  1.279331e+10  1.312082e+10  2.914286e+06
2    1.715220e+11  1.763250e+11  1.830250e+11  1.901630e+11  3.841176e+07
3             NaN           NaN           NaN           NaN           NaN
4    3.129538e+09  3.127550e+09           NaN           NaN  7.438017e+04
..            ...           ...           ...           ...           ...
180  4.386315e+10  4.589732e+10  4.738384e+10  4.784927e+10  3.379310e+06
181  4.609038e+10  4.977761e+10  5.380959e+10  5.811436e+10  2.900000e+07
182  7.218245e+08  7.360383e+08  7.529991e+08           NaN  3.000000e+05
183  2.302438e+10  2.420595e+10  2.542227e+10  2.624127e+10  1.538462e+07
184  1.165789e+10  1.218064e+10  1.264939e+10  1.278517e+10  1.500000e+07

[185 rows x 64 columns]

In [51]:
# d) 
joindata['AvgGDP']=joindata['Country'].mean()

KeyError: 'GDP'

In [ ]:
# e)
joindata['RenewableInd']=

In [ ]:
# f)
continent_dict={'China':'Asia',
               'United States': 'North America',
               'Japan':'Asia',
               'United Kingdom':'Europe',
               'Argentina':'South America',
               'Colombia':'South America',
               'Canada': 'North America',
               'Germany':'Europe',
               'India':'Asia',
               'South Korea':'Asia',
               'Italy':'Europe',
               'Algeria': 'Africa',
               'Indonesia':'Asia',
               'Morocco':'Africa',
               'Sudan':'Africa,
               'New Zealand':'Australia',
               'Australia':'Australia',
               'South Africa':'Africa'
               }
continent=df.DataFrame()