In [15]:
import pandas as pd
import numpy as np

In [16]:
data = pd.read_parquet('G:/My Drive/Master-Data-Science/Semester_1/Data_Mining/Projek/DataSet/bedutil_02_timeseries_facility.parquet')

In [17]:
data.head()

,date,hospital,state,beds_nonicu,util_nonicu,beds_icu,util_icu,vent,util_vent
0,2023-09-07,Hospital Sultanah Nora Ismail,Johor,598.0,78.929766,12.0,83.333333,51.0,19.607843
1,2023-09-07,Hospital Sultanah Aminah,Johor,969.0,111.145511,30.0,86.666667,75.0,54.666667
2,2023-09-07,Hospital Permai,Johor,1132.0,53.091873,0.0,NaN,0.0,NaN
3,2023-09-07,Hospital Sultan Ismail Johor Bahru,Johor,653.0,118.683002,24.0,79.166667,45.0,42.222222
4,2023-09-07,Hospital Enche' Besar Hajjah Khalsom,Johor,372.0,97.043011,10.0,0.000000,45.0,0.000000

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52746 entries, 0 to 52745
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         52746 non-null  object
 1   hospital     52746 non-null  object
 2   state        52746 non-null  object
 3   beds_nonicu  44466 non-null  float64
 4   util_nonicu  43215 non-null  float64
 5   beds_icu     44467 non-null  float64
 6   util_icu     21442 non-null  float64
 7   vent         44467 non-null  float64
 8   util_vent    24070 non-null  float64
dtypes: float64(6), object(3)
memory usage: 3.6+ MB

In [19]:
data['date'] = pd.to_datetime(data['date'])
data['state'] = data['state'].astype('category')
data['hospital'] = data['hospital'].astype('category')

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52746 entries, 0 to 52745
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         52746 non-null  datetime64[ns]
 1   hospital     52746 non-null  category
 2   state        52746 non-null  category
 3   beds_nonicu  44466 non-null  float64
 4   util_nonicu  43215 non-null  float64
 5   beds_icu     44467 non-null  float64
 6   util_icu     21442 non-null  float64
 7   vent         44467 non-null  float64
 8   util_vent    24070 non-null  float64
dtypes: category(2), datetime64[ns](1), float64(6)
memory usage: 3.0 MB

In [71]:
data_sort.head(50)

,date,hospital,state,beds_nonicu,util_nonicu,beds_icu,util_icu,vent,util_vent
64,2023-09-07,Pusat Perubatan Universiti Malaya,Perak,1064.0,79.323308,33.0,84.848485,86.0,75.581395
213,2023-09-08,Pusat Perubatan Universiti Malaya,Perak,1064.0,77.913534,33.0,84.848485,86.0,74.418605
362,2023-09-09,Pusat Perubatan Universiti Malaya,Perak,1064.0,75.939850,33.0,75.757576,86.0,76.744186
511,2023-09-10,Pusat Perubatan Universiti Malaya,Perak,1064.0,70.676692,33.0,84.848485,86.0,77.906977
660,2023-09-11,Pusat Perubatan Universiti Malaya,Perak,1064.0,75.375940,33.0,87.878788,86.0,79.069767
809,2023-09-12,Pusat Perubatan Universiti Malaya,Perak,1064.0,77.349624,33.0,87.878788,86.0,73.255814
958,2023-09-16,Pusat Perubatan Universiti Malaya,Perak,1064.0,71.522556,33.0,78.787879,86.0,81.395349
1107,2023-09-17,Pusat Perubatan Universiti Malaya,Perak,1064.0,73.778195,33.0,84.848485,86.0,79.069767
1256,2023-09-18,Pusat Perubatan Universiti Malaya,Perak,1064.0,71.804511,33.0,84.848485,86.0,76.744186
1405,2023-09-19,Pusat Perubatan Universiti Malaya,Perak,1064.0,76.221805,33.0,81.818182,86.0,80.232558
1554,2023-09-20,Pusat Perubatan Universiti Malaya,Perak,1064.0,79.981203,33.0,84.848485,86.0,76.744186
1703,2023-09-21,Pusat Perubatan Universiti Malaya,Perak,1064.0,81.578947,33.0,81.818182,86.0,76.744186
1852,2023-09-22,Pusat Perubatan Universiti Malaya,Perak,1064.0,81.390977,33.0,81.818182,86.0,77.906977
48489,2023-09-23,Pusat Perubatan Universiti Malaya,Perak,1064.0,75.281955,33.0,72.727273,86.0,82.558140
2001,2023-09-24,Pusat Perubatan Universiti Malaya,Perak,1064.0,72.368421,33.0,78.787879,86.0,61.627907
2150,2023-09-25,Pusat Perubatan Universiti Malaya,Perak,1064.0,74.248120,33.0,84.848485,86.0,75.581395
48638,2023-09-26,Pusat Perubatan Universiti Malaya,Perak,1064.0,78.759398,33.0,84.848485,86.0,72.093023
2299,2023-09-27,Pusat Perubatan Universiti Malaya,Perak,1064.0,82.048872,33.0,78.787879,86.0,70.930233
2448,2023-09-28,Pusat Perubatan Universiti Malaya,Perak,1064.0,82.048872,33.0,81.818182,86.0,74.418605
2597,2023-09-29,Pusat Perubatan Universiti Malaya,Perak,1064.0,0.000000,33.0,84.848485,86.0,65.116279
2746,2023-09-30,Pusat Perubatan Universiti Malaya,Perak,1064.0,77.255639,33.0,81.818182,86.0,73.255814
2895,2023-10-01,Pusat Perubatan Universiti Malaya,Perak,1064.0,74.436090,33.0,81.818182,86.0,76.744186
3044,2023-10-02,Pusat Perubatan Universiti Malaya,Perak,1064.0,78.007519,33.0,84.848485,86.0,70.930233
3193,2023-10-03,Pusat Perubatan Universiti Malaya,Perak,1064.0,77.161654,33.0,81.818182,86.0,66.279070
3342,2023-10-04,Pusat Perubatan Universiti Malaya,Perak,1064.0,77.161654,33.0,84.848485,86.0,74.418605
3491,2023-10-05,Pusat Perubatan Universiti Malaya,Perak,1064.0,77.067669,33.0,72.727273,86.0,61.627907
48787,2023-10-06,Pusat Perubatan Universiti Malaya,Perak,1064.0,80.733083,33.0,75.757576,86.0,75.581395
3640,2023-10-07,Pusat Perubatan Universiti Malaya,Perak,1064.0,76.033835,33.0,78.787879,86.0,61.627907
3789,2023-10-08,Pusat Perubatan Universiti Malaya,Perak,1064.0,76.033835,33.0,81.818182,86.0,68.604651
3938,2023-10-09,Pusat Perubatan Universiti Malaya,Perak,1064.0,78.101504,33.0,0.000000,86.0,0.000000
4087,2023-10-10,Pusat Perubatan Universiti Malaya,Perak,1064.0,76.879699,33.0,72.727273,86.0,61.627907
4236,2023-10-11,Pusat Perubatan Universiti Malaya,Perak,1064.0,81.672932,33.0,78.787879,86.0,69.767442
4385,2023-10-12,Pusat Perubatan Universiti Malaya,Perak,1064.0,81.296992,33.0,78.787879,86.0,70.930233
4534,2023-10-13,Pusat Perubatan Universiti Malaya,Perak,1064.0,79.981203,33.0,72.727273,86.0,69.767442
48936,2023-10-14,Pusat Perubatan Universiti Malaya,Perak,1064.0,74.342105,33.0,0.000000,86.0,0.000000
4683,2023-10-15,Pusat Perubatan Universiti Malaya,Perak,1064.0,72.838346,33.0,0.000000,86.0,0.000000
4832,2023-10-16,Pusat Perubatan Universiti Malaya,Perak,1064.0,66.541353,33.0,72.727273,86.0,69.767442
4981,2023-10-17,Pusat Perubatan Universiti Malaya,Perak,1064.0,79.887218,33.0,75.757576,86.0,70.930233
5130,2023-10-18,Pusat Perubatan Universiti Malaya,Perak,1064.0,80.263158,33.0,78.787879,86.0,67.441860
5279,2023-10-19,Pusat Perubatan Universiti Malaya,Perak,1064.0,85.432331,33.0,69.696970,86.0,73.255814
5428,2023-10-20,Pusat Perubatan Universiti Malaya,Perak,1064.0,82.800752,33.0,84.848485,86.0,70.930233
5577,2023-10-21,Pusat Perubatan Universiti Malaya,Perak,1064.0,76.597744,33.0,84.848485,86.0,65.116279
5726,2023-10-22,Pusat Perubatan Universiti Malaya,Perak,1064.0,74.060150,33.0,78.787879,86.0,69.767442
5875,2023-10-23,Pusat Perubatan Universiti Malaya,Perak,1064.0,76.879699,33.0,84.848485,86.0,80.232558
6024,2023-10-24,Pusat Perubatan Universiti Malaya,Perak,1064.0,79.699248,33.0,72.727273,86.0,62.790698
6173,2023-10-25,Pusat Perubatan Universiti Malaya,Perak,1064.0,82.706767,33.0,81.818182,86.0,79.069767
6322,2023-10-26,Pusat Perubatan Universiti Malaya,Perak,1064.0,80.545113,33.0,84.848485,86.0,68.604651
6471,2023-10-27,Pusat Perubatan Universiti Malaya,Perak,1064.0,79.887218,33.0,78.787879,86.0,76.744186
6620,2023-10-28,Pusat Perubatan Universiti Malaya,Perak,1064.0,78.289474,33.0,72.727273,86.0,75.581395
6769,2023-10-29,Pusat Perubatan Universiti Malaya,Perak,1064.0,76.033835,33.0,81.818182,86.0,70.930233

In [24]:
data_sort = data.sort_values(by=['hospital', 'date'])
data_sort.head()

,date,hospital,state,beds_nonicu,util_nonicu,beds_icu,util_icu,vent,util_vent
64,2023-09-07,Hospital Raja Permaisuri Bainun,Perak,1064.0,79.323308,33.0,84.848485,86.0,75.581395
213,2023-09-08,Hospital Raja Permaisuri Bainun,Perak,1064.0,77.913534,33.0,84.848485,86.0,74.418605
362,2023-09-09,Hospital Raja Permaisuri Bainun,Perak,1064.0,75.939850,33.0,75.757576,86.0,76.744186
511,2023-09-10,Hospital Raja Permaisuri Bainun,Perak,1064.0,70.676692,33.0,84.848485,86.0,77.906977
660,2023-09-11,Hospital Raja Permaisuri Bainun,Perak,1064.0,75.375940,33.0,87.878788,86.0,79.069767

In [27]:
test_data = data_sort.fillna(method='ffill')
test_data.head()

C:\Users\Hathim\AppData\Local\Temp\ipykernel_972\2203605252.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  test_data = data_sort.fillna(method='ffill')

,date,hospital,state,beds_nonicu,util_nonicu,beds_icu,util_icu,vent,util_vent
64,2023-09-07,Hospital Raja Permaisuri Bainun,Perak,1064.0,79.323308,33.0,84.848485,86.0,75.581395
213,2023-09-08,Hospital Raja Permaisuri Bainun,Perak,1064.0,77.913534,33.0,84.848485,86.0,74.418605
362,2023-09-09,Hospital Raja Permaisuri Bainun,Perak,1064.0,75.939850,33.0,75.757576,86.0,76.744186
511,2023-09-10,Hospital Raja Permaisuri Bainun,Perak,1064.0,70.676692,33.0,84.848485,86.0,77.906977
660,2023-09-11,Hospital Raja Permaisuri Bainun,Perak,1064.0,75.375940,33.0,87.878788,86.0,79.069767

In [63]:
data.sort_values(by=['state', 'date'], inplace=True)
hosp_list = pd.DataFrame({
    'state': [],
    'hospital': []
})

for state in data['state'].unique():
    for i in data[data['state'] == state].hospital.unique():
        new_row = pd.DataFrame({'state': [state], 'hospital': [i]})
        hosp_list = pd.concat([hosp_list, new_row], ignore_index=True)

hosp_list

                 state                                 hospital
0                Johor            Hospital Sultanah Nora Ismail
1                Johor                 Hospital Sultanah Aminah
2                Johor                          Hospital Permai
3                Johor       Hospital Sultan Ismail Johor Bahru
4                Johor     Hospital Enche' Besar Hajjah Khalsom
..                 ...                                      ...
144  W.P. Kuala Lumpur  Hospital Universiti Kebangsaan Malaysia
145  W.P. Kuala Lumpur        Pusat Perubatan Universiti Malaya
146        W.P. Labuan                          Hospital Labuan
147     W.P. Putrajaya                       Hospital Putrajaya
148     W.P. Putrajaya                   Institut Kanser Negara

[149 rows x 2 columns]

In [67]:
hosp_list.hospital.duplicated().sum()

0